-- AlterTable
ALTER TABLE `portfolio` MODIFY `type` ENUM('REELS', 'TVC', 'SOCIAL_MEDIA_ADS', 'SHORT_FILMS', 'DOCUMENTARY', 'MUSIC_VIDEO', 'CORPORATE_FILMS', 'VLOGS', 'PODCAST', 'BRANDED_CONTENT', 'TRAINING_VIDEO', 'YOUTUBE_INFLUENCERS_EDIT') NOT NULL DEFAULT 'REELS';
