name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.EC2_HOST }}"
          username: "${{ secrets.EC2_USER }}"
          key: "${{ secrets.EC2_SSH_KEY }}"
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/ubuntu/app/YourFirstClipAPI
            git pull origin main
            npm install
            pm2 restart all
